# Author: Matthias Frey
# Date:   March 2018

import h5py
import numpy as np

class H5Parser:
    
    def __init__(self):
        """
        Constructor.
        
        Parameters
        ----------
        None
        """
        self.__filename = ''
        self.__h5f = ''
        self.__nsteps = 0
    
    def parse(self, fname, info = False):
        """
        Read a H5 file generated by OPAL
        
        Parameters
        ----------
        fname       (str)   H5 filename
        info=False  (bool)  print H5 file summary
        
        Returns
        -------
        None
        """
        self.__filename = fname
        self.__h5f = h5py.File(fname, 'r')
        
        if self.__h5f:
            self.__nsteps = len(self.__h5f.keys())

            if info:                
                print ( self.__str__() )
        else:
            raise H5ParseError("Cannot read '" + fname + "'")
        
    
    def getNSteps(self):
        """
        Number of steps in file.
        
        Parameters
        ----------
        None
        
        Returns
        -------
        the number of steps
        """
        return self.__nsteps
    
    
    def getStepAttributes(self, step = 0):
        """
        Attributes names of a step.
        
        Parameters
        ----------
        step=0  (int)   of file
        
        Returns
        -------
        a list of strings of all attribute names of a step
        """
        path = 'Step#' + str(step)
        return list(self.__h5f[path].attrs.keys())
    
    
    def getStepDatasets(self, step = 0):
        """
        All step dataset names.
        
        Parameters
        ----------
        step=0  (int)   of file
        
        Returns
        -------
        a list of strings of all step datasets
        """
        path = 'Step#' + str(step)
        return list(self.__h5f[path].keys())
    
    
    def getStepDataset(self, dsetName, step=0):
        """
        Obtain the data of a step.
        
        Parameters
        ----------
        dsetName (str)   name of dataset
        step=0   (int)   of file
        
        Returns
        -------
        a list of a dataset of a step (check with getStepDatasets())
        """
        if step > self.__nsteps - 1:
            raise H5OverflowError('Only ' + str(self.__nsteps - 1) + ' steps.')
        elif step < 0:
            raise H5OverflowError("Negative step number: '" + str(step) + "'")
        
        if not dsetName in self.getStepDatasets(step):
            raise H5DatasetError("'" + dsetName + "' is not a dataset of this step")
        
        data = []
        path = 'Step#' + str(step) + '/' + dsetName
        return np.asarray(self.__h5f[path])
    
    
    def getStepAttribute(self, attrName, step=0):
        """
        Obtain the attribute data of a step.
        
        Parameters
        ----------
        attrName (str)   name of attribute
        step=0   (int)   of file
        
        Returns
        -------
        
        """
        if step > self.__nsteps - 1:
            raise H5OverflowError('Only ' + str(self.__nsteps - 1) + ' steps.')
        elif step < 0:
            raise H5OverflowError("Negative step number: '" + str(step) + "'")
        
        if not attrName in self.getStepAttributes(step):
            raise H5AttributeError("'" + attrName + "' is not a attribute of this step")
        
        data = []
        path = 'Step#' + str(step)
        data = self.__h5f[path].attrs[attrName]
        return data[:]
    
    
    def getGlobalAttributes(self):
        """
        All attributes of root.
        
        Parameters
        ----------
        Nones
        
        Returns
        -------
        a list of strings of all root attributes
        """
        return list(self.__h5f.attrs.keys())
    
    
    def getGlobalAttribute(self, attrName):
        """
        Obtain value of global attribute.
        
        Parameters
        ----------
        attrName (str)   name of flobal attribute
        
        Returns
        -------
        value as string.
        """
        value = self.__h5f.attrs[attrName]
        # 7. March 2018
        # https://stackoverflow.com/questions/37016946/remove-b-character-do-in-front-of-a-string-literal-in-python-3
        return value.decode("utf-8")
    
    
    def __str__(self):
        """
        Print file summary.
        
        Returns
        -------
        a summary of the file.
        """
        info = '\nNumber of steps:    ' + str(self.__nsteps) + '\n\n'
        
        info += 'Global attributes:\n'
        info += '------------------\n'
        for i, attr in enumerate(sorted(self.getGlobalAttributes())):
            info += '  {:20}'.format(attr)
            
            if (i+1) % 5 == 0:
                info += '\n'
        
        info += '\n\nStep attributes:\n'
        info += '----------------\n'
        for i, attr in enumerate(sorted(self.getStepAttributes())):
            info += '  {:20}'.format(attr)
            
            if (i+1) % 5 == 0:
                info += '\n'
        
        info += '\n\nStep datasets:\n'
        info += '--------------\n'
        for i, attr, in enumerate(sorted(self.getStepDatasets())):
            info += '  {:20}'.format(attr)
            
            if (i+1) % 5 == 0:
                info += '\n'
        
        return info + '\n'