import json
import os
import numpy as np
import re

class OptimizerParser:
    """ Parsing of JSON files generated by the OPAL optimizer
    
    Methods
    ----------
    OptimizerParser     : Check a directory for .json files and read in their format
    readGeneration      : Read a specific generation file
    getIndividual       : Obtain an individual [design variables, objectives, ID]
    getIndividualWithID : Obtain an individual with a specific ID [design variables, objectives, ID]
    getDesignVariables  : Returns all design variable names
    getObjectives       : Returns all objective names
    getBounds           : Returns all or design variable specific lower and upper bound
    getConstraints      : Returns all constraints (strings) in a list
    getAllInput         : Returns all design variable values,
                          each column is a design variable
    getAllOutput        : Returns all objective values,
                          each column is an objective
    getIDs              : Return all IDs of all individuals
    
    Private Members
    ---------------
    __ids           ([])            list of all individual IDs of a generation
    __dvar_values   (np.matrix)     list of all design variables values for each ID
                                    (order corresponds to __ids)
    __obj_values    (np.matrix)     list of all objective values for each ID
                                    (order corresponds to __ids)
    __obj_names                     specifies columns in self.__obj_values
    __dvar_names                    specifies columns in self.__dvar_values
    
    Returns
    -------
    None

    Notes
    -----
    None

    Examples
    --------
    Supports following JSON files:
    
    =====================================================
    {
        "name": "opt-pilot",
        "dvar-bounds": {
                "benergy": [ 0.071, 0.072 ],
                "phiinit": [ 106, 114 ],
                "prinit": [ -0.02, -0.01 ],
                "rinit": [ 2000, 2060 ]
        }
        ,
        "constraints": [
                "dpeak1 > 0.0",
                "dpeak2 > 0.0"
        ]
        ,
        "solutions": [
        {
                "ID": 0,
                "obj":
                {
                        "dpeak1": 10.37,
                        "dpeak2": 5.43,
                        "dpeak3_5": 14.1095
                }
                ,
                "dvar":
                {
                        "benergy": 0.0718672,
                        "phiinit": 113.653,
                        "prinit": -0.0191565,
                        "rinit": 2018.26
                }
        }
        ,
        {
                "ID": 18,
                "obj":
                {
                        "dpeak1": 5.95,
                        "dpeak2": 4.75,
                        "dpeak3_5": 17.6668
                }
                ,
                "dvar":
                {
                        "benergy": 0.0715704,
                        "phiinit": 110.517,
                        "prinit": -0.0122177,
                        "rinit": 2035.32
                }
        }
        ,
        {
                "ID": 2,
                "obj":
                {
                        "dpeak1": 1.84,
                        "dpeak2": 6.04,
                        "dpeak3_5": 19.2461
                }
                ,
                "dvar":
                {
                        "benergy": 0.0711942,
                        "phiinit": 107.097,
                        "prinit": -0.0198867,
                        "rinit": 2034.75
                }
        }
        ]
    }
    
    
    
    {
        "name": "opt-pilot",
        "OPAL version": "2.0.0",
        "git revision": "1849b7e5130657e8be50d524de0f6c50134f330a",
        "dvar-bounds": {
            "MX": "[ 16, 32 ]",
            "nstep": "[ 10, 40 ]"
        },
        "constraints": [
            "statVariableAt('rms_x',0.0) > 0",
            "statVariableAt('rms_x',0.0) > 0.001"
        ],
        "population": {
            "0": {
                "obj": {
                    "dpeak1": 10.37,
                    "dpeak2": 5.43,
                    "dpeak3_5": 14.1095
                },
                "dvar": {
                    "benergy": 0.0718672,
                    "phiinit": 113.653,
                    "prinit": -0.0191565,
                    "rinit": 2018.26
                }
            },
            "18": {
                "obj": {
                    "dpeak1": 5.95,
                    "dpeak2": 4.75,
                    "dpeak3_5": 17.6668
                },
                "dvar": {
                    "benergy": 0.0715704,
                    "phiinit": 110.517,
                    "prinit": -0.0122177,
                    "rinit": 2035.32
                }
                },
            "2": {
                "obj": {
                    "dpeak1": 1.84,
                    "dpeak2": 6.04,
                    "dpeak3_5": 19.2461
                },
                "dvar": {
                    "benergy": 0.0711942,
                    "phiinit": 107.097,
                    "prinit": -0.0198867,
                    "rinit": 2034.75
                }
            }
        }
    }
    =====================================================
    
    
    import OptimizerParser as optreader
    import sys
    
    try:
        
        # 1. Find all .json files of a directory, e.g. "./"
        optjson = optreader.OptimizerParser("./")
        
        # 2. Read in a generation file, e.g. 1  
        optjson.readGeneration(1)
        
        # 3. Get all design variables
        dvars = optjson.getDesignVariables()
        
        print ( "Design variables: ", dvars )
        
        # 4. Get design variable bounds
        bounds = optjson.getBounds()
        
        print ( "Bounds: ", bounds )
        
        # 4a. Get only bounds of a specific design variable
        bound = optjson.getBounds(dvars[2])
        lower = bound[0]
        upper = bound[1]
    
        print ( "dvar: " + dvars[1] + "\n"
                " lower bound: " + str(lower) + "\n"
                " upper bound: " + str(upper))
        
        # 5. Get all objectives
        objs = optjson.getObjectives()
        
        print ( "Objectives: ", objs )
        
        # 6. Get all constraints
        constr = optjson.getConstraints()
    
        print ("Constraints:\n\t" + constr[0] + "\n\t" + constr[1])
        
        # 7. Get an individual
        print ( optjson.getIndividual(0) )
        
        # 8. Get an individual with specific ID
        print ( optjson.getIndividualWithID(18) )
        
        # raise error
        print ( optjson.getIndividualWithID(1) )
    
    except:
        print ( sys.exc_info()[1] )

    """
    
    
    ##
    # @param directory to json files
    def __init__(self, directory):
        """ Parse a generation file

        Parameters
        ----------
        directory     : where the .json files are
    
        Returns
        -------
        an OptimizerParser object
    
        Notes
        -----
        Raises a runtime error if
            - there are several several different basenames
            - no json file is found
    
        Examples
        --------
        None
        """
        
        self.__nJsonFiles = 0;
        self.__directory = directory
        self.__basename = ""
        self.__nOptimizers = -1
        
        self.__version_supported = {
            '2.1.0':    self.__readGeneration_version_2_1_0
        }
        
        self.__loaded_generation = -1
        self.__loaded_optimizer  = -1
        
        tbasename = ""
        testfile = ""
        for f in os.listdir(directory):
            if f.endswith(".json"):
                self.__nJsonFiles += 1
                
                if self.__nJsonFiles == 1:
                    testfile = f
                
                tbasename = os.path.basename(f)
                split = re.split('_|.json', tbasename)
                tbasename = '_' + split[1] + '_'
                
                self.__nOptimizers = max(self.__nOptimizers, int(split[2]))
                
                # check if only one type of simulation
                if self.__basename != "" and tbasename != self.__basename:
                    raise RuntimeError("Several simulations with different name!")
                
                self.__basename = tbasename
        
        if self.__nJsonFiles == 0:
            raise RuntimeError("No json file found in directory '" + directory + "'.")
        
        self.__nOptimizers += 1
        print ( "Found " + str(self.__nJsonFiles) + " json files from " +
                str(self.__nOptimizers) +  " optimizers." )


    @property
    def num_optimizers(self):
        return self.__nOptimizers


    ##
    def getNumOfGenerations(self):
        return int(self.__nJsonFiles / self.__nOptimizers)
    
    ##
    def readGeneration(self, gen, opt=0):
        """ Parse a generation file

        Parameters
        ----------
        gen     : the generation number
        opt     : the optimizer number (default: 0)
    
        Returns
        -------
        None
    
        Notes
        -----
        Raises a runtime error if generation file doesn't exist
    
        Examples
        --------
        None
        """
        
        if not self.__loaded_generation == gen or \
            not self.__loaded_optimizer == opt:
            self.__loaded_generation = gen
            self.__loaded_optimizer == opt
        else:
            return
        
        filename = os.path.join(self.__directory,
                                str(gen) + self.__basename + str(opt) + '.json')
        
        if not os.path.isfile(filename):
            raise IOError("File '" + filename + "' does not exist.")
        
        
        # clear old data
        self.__ids         = []
        self.__dvar_values = np.empty((0, 0))
        self.__dvar_names  = []
        self.__obj_values  = np.empty((0, 0))
        self.__obj_names   = []
        self.__dvarBounds  = {} # for each generation file the same
        self.__constraints = [] # for each generation file the same
        
        data = json.load(open(filename))
        
        tag = 'OPAL version'
        if tag in data.keys():
            version = data[tag]
            
            if version in self.__version_supported.keys():
                self.__version_supported[version](data)
            else:
                raise IOError('No version ' + version + ' supported.')
        else:
            self.__readGeneration_version_2_0_0(data)
    
    
    ##
    def getIndividual(self, ind):
        """ Get individual in a list of [dvars, objs, ID]

        Parameters
        ----------
        ind     : the individual number (not the ID)
        opt     : the optimizer number (default: 0)
    
        Returns
        -------
        a list containing [design variables, objectives, ID]
    
        Notes
        -----
        Raises an index error if individual number is out of bounds
    
        Examples
        --------
        None
        """
        
        if self.__loaded_generation < 0:
            raise RuntimeError("No generation file loaded.")
        
        if ind > len(self.__ids) - 1 or ind < 0:
            raise IndexError("Individual number is out of bounds.")
        
        data = list(self.__dvar_values[ind, :]) + list(self.__obj_values[ind, :])
        data.append(self.__ids[ind])
        return data
    
    
    ##
    def getIndividualWithID(self, ID):
        """ Get invdividual with ID

        Parameters
        ----------
        ID     :    for which we want the data
    
        Returns
        -------
        a list containing [design variables, objectives, ID]
    
        Notes
        -----
        Raises a runtime error if there's no individual with given ID
    
        Examples
        --------
        None
        """
        idx = self.getIndexOfID(ID)
        
        data = list(self.__dvar_values[idx, :]) + list(self.__obj_values[idx, :])
        
        data.append(self.__ids[idx])
        return data
    
    
    ##
    def getIndexOfID(self, ID):
        """
        Returns
        -------
        the index of the individual with certain ID
        """
        if self.__loaded_generation < 0:
            raise RuntimeError("No generation file loaded.")
        
        if ID not in self.__ids:
            raise RuntimeError("An individual with ID " + str(ID) + " is not present.")
        return self.__ids.index(ID)
        
    
    ##
    def getDesignVariables(self):
        """ Obtain names of all design variables

        Parameters
        ----------
        None
    
        Returns
        -------
        a list containing all design variable names
    
        Notes
        -----
        None
    
        Examples
        --------
        None
        """
        if self.__loaded_generation < 0:
            raise RuntimeError("No generation file loaded.")
        
        return self.__dvar_names
    
    
    ##
    def getObjectives(self):
        """ Obtain names of all objectives

        Parameters
        ----------
        None
    
        Returns
        -------
        a list containing all design variable names
    
        Notes
        -----
        None
    
        Examples
        --------
        None
        """
        if self.__loaded_generation < 0:
            raise RuntimeError("No generation file loaded.")
        
        return self.__obj_names
    
    
    ##
    def getBounds(self, dvar = ''):
        """ Obtain the design variable bounds
        
        Parameters
        ----------
        dvar(str)   : design variable or ''
        
        Returns
        -------
        If dvar == '' it returns the whole dictionary of
        design variables and their bounds otherwise
        it returns the bounds of the given design varible
        
        Notes
        -----
        Raises an exception if design variable unknown
        
        Examples
        --------
        None
        """
        if self.__loaded_generation < 0:
            raise RuntimeError("No generation file loaded.")
        
        if dvar == '':
            return self.__dvarBounds
        elif dvar not in self.__dvarBounds:
            raise RuntimeError("Unknown design variable '" + dvar + "'.")
        else:
            return self.__dvarBounds[dvar]
        
    
    ##
    def getConstraints(self):
        """ Obtain the constraints of the simulation. They are
            formulas written as strings
            
        Parameters
        ----------
        None
        
        Returns
        -------
        A list of strings containing the constraints
        
        Notes
        -----
        None
        
        Examples
        --------
        None
        """
        if self.__loaded_generation < 0:
            raise RuntimeError("No generation file loaded.")
        
        return self.__constraints
    
    
    ##
    def getAllInput(self):
        """ Obtain all design variable input.
        
        Parameters
        ----------
        None
        
        Returns
        -------
        a ndarray where each column corresponds to the values
        of a design variable
        
        Notes
        -----
        None
        
        Examples
        --------
        None
        """
        if self.__loaded_generation < 0:
            raise RuntimeError("No generation file loaded.")
        
        return self.__dvar_values
    
    
    ##
    def getAllOutput(self):
        """ Obtain all objective output.
        
        Parameters
        ----------
        None
        
        Returns
        -------
        a ndarray where each column corresponds to the values
        of an objective
        
        Notes
        -----
        None
        
        Examples
        --------
        None
        """
        if self.__loaded_generation < 0:
            raise RuntimeError("No generation file loaded.")
        
        return self.__obj_values
    
    
    ##
    def getIDs(self):
        """ Obtain all individual IDs.
        
        Parameters
        ----------
        None
        
        Returns
        -------
        a list of IDs
        
        Examples
        --------
        None
        """
        if self.__loaded_generation < 0:
            raise RuntimeError("No generation file loaded.")
        
        return self.__ids
    
    
    ##
    def __readGeneration_version_2_1_0(self, data):
        """ Read in data

        Parameters
        ----------
        data    : a generation file

        Returns
        -------
        None

        Examples
        --------
        None
        """
        self.__dvarBounds = data["dvar-bounds"]
        self.__constraints = data["constraints"]
        
        population = data["population"]
        
        # get first individual id
        first_ind = next(iter(population))
        
        nDvars = len(population[first_ind]['dvar'])
        nObjs  = len(population[first_ind]['obj'])
        nInds  = len(population)
        
        self.__dvar_values = np.zeros((nInds, nDvars))
        self.__obj_values  = np.zeros((nInds, nObjs))
        
        i = 0
        for ind in sorted(population.keys()):
            self.__ids.append(int(ind))
            
            k = 0
            for dvar, value in sorted(population[ind]['dvar'].items()):
                self.__dvar_values[i, k] = float(value)
                k += 1
                if i == 0:
                    self.__dvar_names.append( dvar )
            
            k = 0
            for obj, value in sorted(population[ind]['obj'].items()):
                self.__obj_values[i, k] = float(value)
                k += 1
                if i == 0:
                    self.__obj_names.append( obj )
            i += 1
    
    
    ##
    def __readGeneration_version_2_0_0(self, data):
        """ Read in data

        Parameters
        ----------
        data    : a generation file

        Returns
        -------
        None
    
        Notes
        -----
        Storage of columns: dvars, objs, ID
    
        Examples
        --------
        None
        """
        self.__dvarBounds = data["dvar-bounds"]
        self.__constraints = data["constraints"]
        
        individuals = data["solutions"]
        
        nDvars = len(individuals[0]['dvar'])
        nObjs  = len(individuals[0]['obj'])
        nInds  = len(individuals)
        
        self.__dvar_values = np.zeros((nInds, nDvars))
        self.__obj_values  = np.zeros((nInds, nObjs))
        
        for i, entry in enumerate(individuals):
            for key in entry.keys():
                if key == 'dvar':
                    k = 0
                    for dvar, value in sorted(entry[key].items()):
                        self.__dvar_values[i, k] = float(value)
                        k += 1
                        if i == 0:
                            self.__dvar_names.append( dvar )
                elif key == 'obj':
                    k = 0
                    for obj, value in sorted(entry[key].items()):
                        self.__obj_values[i, k] = float(value)
                        k += 1
                        if i == 0:
                            self.__obj_names.append( obj )
                elif key == 'ID':
                    self.__ids.append( int(entry[key]) )
