##
# @file visualize.py
# @author Matthias Frey
# @date 14. October 2016, LBNL
# @version 1.1 (21. Dec. 2016)
# 
# @pre Python >= 2.7
# @details Plot the electric self-field, density and self-field
# potential using the yt framework.
# 1. mpirun -np #cores testSolver
# 2. python visualize.py (make sure you sourced the yt directory $YT_DIR/yt-x86_64/bin/activate)
# @brief Slice plots of plotfiles generated by writePlotFile.H

import os
import yt
import argparse

from tools import doSlicePlot, doProjectionPlot

try:
    parser = argparse.ArgumentParser(description='Visualize BoxLib grid data.')
    parser.add_argument('--zoom',
                        help='zoom factor of images (default: 1)',
                        default=1,
                        type=float,
                        nargs=1)
    
    parser.add_argument('--pltfile',
                        help='plot file',
                        type=str)
    
    args = parser.parse_args()
    
    zoom = args.zoom
    
    pltfile = args.pltfile
    
    print ( pltfile )
    
    ds = yt.load(pltfile, dataset_type='opal')
    
    ds.print_stats()
    
    print ("Field list:", ds.field_list)
    print ("Derived field list:", ds.derived_field_list)    
    
    
    doSlicePlot(ds, 'z', 'rho', 'C/m**3', zoom, 'gray')
    
    doSlicePlot(ds, 'y', 'rho', 'C/m**3', zoom, 'gray')
    
    doSlicePlot(ds, 'x', 'rho', 'C/m**3', zoom, 'gray')
    
    doProjectionPlot(ds, 'x', 'rho', 'C/m**3', zoom, col='gray')
    
    doProjectionPlot(ds, 'y', 'rho', 'C/m**3', zoom, col='gray')
    
    doProjectionPlot(ds, 'z', 'rho', 'C/m**3', zoom, col='gray')
    
    doSlicePlot(ds, 'z', 'Ex', 'V/m', zoom)
    
    doSlicePlot(ds, 'z', 'Ey', 'V/m', zoom)
    
    doSlicePlot(ds, 'x', 'Ez', 'V/m', zoom)
    
    doSlicePlot(ds, 'z', 'potential', 'V', zoom)
    
    doSlicePlot(ds, 'y', 'potential', 'V', zoom)
    
    doSlicePlot(ds, 'x', 'potential', 'V', zoom)
    
    doProjectionPlot(ds, 'z', 'potential', 'V', zoom)
    
    doProjectionPlot(ds, 'y', 'potential', 'V', zoom)
    
    doProjectionPlot(ds, 'x', 'potential', 'V', zoom)

    ad = ds.all_data()
    
    print ( ad.quantities.extrema("rho").in_units('C/m**3') )
    print ( ad.quantities.extrema("Ex").in_units('V/m') )
    print ( ad.quantities.extrema("potential").in_units('V') )
    
except IOError as e:
    print (e.strerror)
