##
# @file visualize.py
# @author Matthias Frey
# @date 14. October 2016, LBNL
# @version 1.1 (21. Dec. 2016)
# 
# @pre Python >= 2.7
# @details Plot the electric self-field, density and self-field
# potential using the yt framework.
# 1. mpirun -np #cores testSolver
# 2. python visualize.py (make sure you sourced the yt directory $YT_DIR/yt-x86_64/bin/activate)
# @brief Slice plots of plotfiles generated by writePlotFile.H

import os
import yt
import argparse
import numpy
import matplotlib.pyplot as plt

from tools import doSlicePlot, doProjectionPlot

try:
    parser = argparse.ArgumentParser(description='Visualize BoxLib grid data.')
    parser.add_argument('--zoom',
                        help='zoom factor of images (default: 1)',
                        default=1,
                        type=float,
                        nargs='?',
                        const=1)
    
    parser.add_argument('--pltfile',
                        help='plot file',
                        type=str)
    
    args = parser.parse_args()
    
    zoom = args.zoom
    
    pltfile = args.pltfile
    
    print ( pltfile )
    
    ds = yt.load(pltfile, dataset_type='boxlib_opal')
    
    ds.print_stats()
    
    print ("Field list:", ds.field_list)
    print ("Derived field list:", ds.derived_field_list)    
    
    
    doSlicePlot(ds, 'z', 'rho', 'C/m**3', zoom, 'gray')
    
    doSlicePlot(ds, 'y', 'rho', 'C/m**3', zoom, 'gray')
    
    doSlicePlot(ds, 'x', 'rho', 'C/m**3', zoom, 'gray')
    
    doProjectionPlot(ds, 'x', 'rho', 'C/m**3', zoom, col='gray')
    
    doProjectionPlot(ds, 'y', 'rho', 'C/m**3', zoom, col='gray')
    
    doProjectionPlot(ds, 'z', 'rho', 'C/m**3', zoom, col='gray')
    
    doSlicePlot(ds, 'z', 'Ex', 'V/m', zoom)
    
    doSlicePlot(ds, 'z', 'Ey', 'V/m', zoom)
    
    doSlicePlot(ds, 'x', 'Ez', 'V/m', zoom)
    
    doSlicePlot(ds, 'z', 'electrostatic_potential', 'V', zoom)
    
    doSlicePlot(ds, 'y', 'electrostatic_potential', 'V', zoom)
    
    doSlicePlot(ds, 'x', 'electrostatic_potential', 'V', zoom)
    
    doProjectionPlot(ds, 'z', 'electrostatic_potential', 'V', zoom)
    
    doProjectionPlot(ds, 'y', 'electrostatic_potential', 'V', zoom)
    
    doProjectionPlot(ds, 'x', 'electrostatic_potential', 'V', zoom)
    
    
    ax = 0 # take a line cut along the x axis
    
    #c = ds.find_max('electrostatic_potential')[1]
    #start = ((-1.0, "cm"), (-0.24, "cm"), (0.0, "cm"))
    #end = ((1.0, "cm"), (-0.24, "cm"), (0.0, "cm"))
    
    start = ((-1.0, "cm"), (0.359375, "cm"), (0.0, "cm"))
    end = ((1.0, "cm"), (0.359375, "cm"), (0.0, "cm"))
    ray = ds.r[start:end]
    
    #print ( 'center : ', c )
    
    srt = numpy.argsort(ray['x'])
    
    plt.plot(numpy.array(ray['x'][srt]),
             numpy.array(ray['electrostatic_potential'][srt]))
    plt.ylabel('electrostatic_potential (V)')
    plt.ticklabel_format(style='sci', axis='y', scilimits=(0,0))
    plt.xlabel('x-axis')
    plt.savefig('line_plot_x_electrostatic_potential_3d.png')
    
    
    plt.close()
    
    plt.plot(numpy.array(ray['x'][srt]),
             numpy.array(ray['Ex'][srt]))
    
    plt.ylabel(r'$\rm{E_x}$ (V/m)')
    plt.ticklabel_format(style='sci', axis='y', scilimits=(0,0))
    plt.xlabel('x-axis')
    plt.savefig('line_plot_x_efield.png')

    ad = ds.all_data()
    
    print ( ad.quantities.extrema("rho").in_units('C/m**3') )
    print ( ad.quantities.extrema("Ex").in_units('V/m') )
    print ( ad.quantities.extrema("electrostatic_potential").in_units('V') )
    
except IOError as e:
    print (e.strerror)
