import json
import os
import numpy as np

class OptPilotJsonReader:
    """ Parsing of JSON files generated by Opt-Pilot

    Parameters
    ----------
    OptPilotJsonReader  : Check a directory for .json files and read in their format
    readGeneration      : Read a specific generation file
    getIndividual       : Obtain an individual [design variables, objectives, ID]
    getIndividualWithID : Obtain an individual with a specific ID [design variables, objectives, ID]
    getDesignVariables  : Returns all design variable names
    getObjectives       : Returns all objective names
    getBounds           : Returns all or design variable specific lower and upper bound
    getConstraints      : Returns all constraints (strings) in a list
    getAllInput         : Returns all design variable values,
                          each column is a design variable
    getAllOutput        : Returns all objective values,
                          each column is an objective
    getIDs              : Return all IDs of all individuals
    
    Returns
    -------
    None

    Notes
    -----
    None

    Examples
    --------
    Assume following JSON file:
    
    =====================================================
    {
        "name": "opt-pilot",
        "dvar-bounds": {
                "benergy": [ 0.071, 0.072 ],
                "phiinit": [ 106, 114 ],
                "prinit": [ -0.02, -0.01 ],
                "rinit": [ 2000, 2060 ]
        }
        ,
        "constraints": [
                "dpeak1 > 0.0",
                "dpeak2 > 0.0"
        ]
        ,
        "solutions": [
        {
                "ID": 0,
                "obj":
                {
                        "dpeak1": 10.37,
                        "dpeak2": 5.43,
                        "dpeak3_5": 14.1095
                }
                ,
                "dvar":
                {
                        "benergy": 0.0718672,
                        "phiinit": 113.653,
                        "prinit": -0.0191565,
                        "rinit": 2018.26
                }
        }
        ,
        {
                "ID": 18,
                "obj":
                {
                        "dpeak1": 5.95,
                        "dpeak2": 4.75,
                        "dpeak3_5": 17.6668
                }
                ,
                "dvar":
                {
                        "benergy": 0.0715704,
                        "phiinit": 110.517,
                        "prinit": -0.0122177,
                        "rinit": 2035.32
                }
        }
        ,
        {
                "ID": 2,
                "obj":
                {
                        "dpeak1": 1.84,
                        "dpeak2": 6.04,
                        "dpeak3_5": 19.2461
                }
                ,
                "dvar":
                {
                        "benergy": 0.0711942,
                        "phiinit": 107.097,
                        "prinit": -0.0198867,
                        "rinit": 2034.75
                }
        }
        ]
    }
    =====================================================
    
    
    import OptPilotJsonReader as optreader
    import sys
    
    try:
        
        # 1. Find all .json files of a directory, e.g. "./"
        optjson = optreader.OptPilotJsonReader("./")
        
        # 2. Read in a generation file, e.g. 1  
        optjson.readGeneration(1)
        
        # 3. Get all design variables
        dvars = optjson.getDesignVariables()
        
        print ( "Design variables: ", dvars )
        
        # 4. Get design variable bounds
        bounds = optjson.getBounds()
        
        print ( "Bounds: ", bounds )
        
        # 4a. Get only bounds of a specific design variable
        bound = optjson.getBounds(dvars[2])
        lower = bound[0]
        upper = bound[1]
    
        print ( "dvar: " + dvars[1] + "\n"
                " lower bound: " + str(lower) + "\n"
                " upper bound: " + str(upper))
        
        # 5. Get all objectives
        objs = optjson.getObjectives()
        
        print ( "Objectives: ", objs )
        
        # 6. Get all constraints
        constr = optjson.getConstraints()
    
        print ("Constraints:\n\t" + constr[0] + "\n\t" + constr[1])
        
        # 7. Get an individual
        print ( optjson.getIndividual(0) )
        
        # 8. Get an individual with specific ID
        print ( optjson.getIndividualWithID(18) )
        
        # raise error
        print ( optjson.getIndividualWithID(1) )
    
    except:
        print ( sys.exc_info()[1] )

    """
    
    
    ##
    # @param directory to json files
    def __init__(self, directory):
        """ Parse a generation file

        Parameters
        ----------
        directory     : where the .json files are
    
        Returns
        -------
        an OptPilotJsonReader object
    
        Notes
        -----
        Raises a runtime error if
            - there are several several different basenames
            - no json file is found
    
        Examples
        --------
        None
        """
        
        self.__nJsonFiles = 0;
        self.__directory = directory
        self.__basename = ""
        self.__table = []
        
        ## name of the columns in the solution data
        #self.__nameToColumnMap = {}
        self.__objNameToColumnMap = {}
        self.__dvarNameToColumnMap = {}
        self.__dvarBounds = {} # for each generation file the same
        self.__constraints = [] # for each generation file the same
        
        self.__nDvars = 0
        self.__nObjs  = 0
        self.__nColumns = 0
        self.__nIndividuals = 0 # the number of individuals varies per generation
        
        tbasename = ""
        testfile = ""
        for f in os.listdir(directory):
            if f.endswith(".json"):
                self.__nJsonFiles += 1
                
                if self.__nJsonFiles == 1:
                    testfile = f
                
                tbasename = os.path.basename(f)
                
                tbasename = "_" + str.split(f, "_", 1)[1]
                
                # check if only one type of simulation
                if self.__basename != "" and tbasename != self.__basename:
                    raise RuntimeError("Several simulations with different name!")
                
                self.__basename = tbasename
        
        if self.__nJsonFiles == 0:
            raise RuntimeError("No json file found in directory '" + directory + "'.")

        # get mapping from first file (all others are the same)
        self.__buildNameToColumnMap(self.__directory + testfile)
        
        print ( "Found " + str(self.__nJsonFiles) + " json files." )
    

    ##
    def getNumOfGenerations(self):
        return self.__nJsonFiles
    
    ##
    def readGeneration(self, gen):
        """ Parse a generation file

        Parameters
        ----------
        gen     : the generation number
    
        Returns
        -------
        None
    
        Notes
        -----
        Raises a runtime error if generation file doesn't exist
    
        Examples
        --------
        None
        """
        
        filename = self.__directory + str(gen) + self.__basename
        
        if not os.path.isfile(filename):
            raise IOError("File '" + filename + "' does not exist.")
        
        self.__table = self.__readJSONData(filename)
    
    
    ##
    def getIndividual(self, ind):
        """ Get invdividual is a list of [dvars, objs, ID]

        Parameters
        ----------
        ind     : the individual number (not the ID)
    
        Returns
        -------
        a list containing [design variables, objectives, ID]
    
        Notes
        -----
        Raises an index error if individual number is out of bounds
    
        Examples
        --------
        None
        """
        
        if ind > self.__nIndividuals - 1 or ind < 0:
            raise IndexError("Individual number is out of bounds.")
        
        return self.__table[ind, :]
    
    
    ##
    def getIndividualWithID(self, ID):
        """ Get invdividual with ID

        Parameters
        ----------
        ID     :    for which we want the data
    
        Returns
        -------
        a list containing [design variables, objectives, ID]
    
        Notes
        -----
        Raises a runtime error if there's no individual with given ID
    
        Examples
        --------
        None
        """
        idx = self.getIndexOfID(ID)
        return self.__table[idx, :]
    
    
    ##
    def getIndexOfID(self, ID):
        """
        Returns
        -------
        the index of the individual with certain ID
        """
        idlist = self.__table[:, self.__nDvars + self.__nObjs].astype(int).tolist()
        
        if ID not in idlist:
            raise RuntimeError("An individual with ID " + str(ID) + " is not present.")
        return idlist.index(ID)
        
    
    ##
    def getDesignVariables(self):
        """ Obtain names of all design variables

        Parameters
        ----------
        None
    
        Returns
        -------
        a list containing all design variable names
    
        Notes
        -----
        None
    
        Examples
        --------
        None
        """
        return sorted(self.__dvarNameToColumnMap.keys())
    
    
    ##
    def getObjectives(self):
        """ Obtain names of all objectives

        Parameters
        ----------
        None
    
        Returns
        -------
        a list containing all design variable names
    
        Notes
        -----
        None
    
        Examples
        --------
        None
        """
        return sorted(self.__objNameToColumnMap.keys())
    
    
    ##
    def getBounds(self, dvar = ''):
        """ Obtain the design variable bounds
        
        Parameters
        ----------
        dvar(str)   : design variable or ''
        
        Returns
        -------
        If dvar == '' it returns the whole dictionary of
        design variables and their bounds otherwise
        it returns the bounds of the given design varible
        
        Notes
        -----
        Raises an exception if design variable unknown
        
        Examples
        --------
        None
        """
        if dvar == '':
            return self.__dvarBounds
        elif dvar not in self.__dvarBounds:
            raise RuntimeError("Unknown design variable '" + dvar + "'.")
        else:
            return self.__dvarBounds[dvar]
        
    
    ##
    def getConstraints(self):
        """ Obtain the constraints of the simulation. They are
            formulas written as strings
            
        Parameters
        ----------
        None
        
        Returns
        -------
        A list of strings containing the constraints
        
        Notes
        -----
        None
        
        Examples
        --------
        None
        """
        return self.__constraints
    
    
    ##
    def getAllInput(self):
        """ Obtain all design variable input.
        
        Parameters
        ----------
        None
        
        Returns
        -------
        a ndarray where each column corresponds to the values
        of a design variable
        
        Notes
        -----
        None
        
        Examples
        --------
        None
        """
        return self.__table[:, 0:self.__nDvars]
    
    
    ##
    def getAllOutput(self):
        """ Obtain all objective output.
        
        Parameters
        ----------
        None
        
        Returns
        -------
        a ndarray where each column corresponds to the values
        of an objective
        
        Notes
        -----
        None
        
        Examples
        --------
        None
        """
        return self.__table[:, self.__nDvars:self.__nDvars+self.__nObjs]
    
    
    ##
    def getIDs(self):
        """ Obtain all individual IDs.
        
        Parameters
        ----------
        None
        
        Returns
        -------
        a list of IDs
        
        Examples
        --------
        None
        """
        return self.__table[:, self.__nDvars + self.__nObjs].astype(int).tolist()
    
    ##
    def __buildNameToColumnMap(self, filename):
        """ Build data structures

        Parameters
        ----------
        filename    : a generation file
    
        Returns
        -------
        None
    
        Notes
        -----
        Assumes the ordering: [u'dvar', u'obj', u'ID']
    
        Examples
        --------
        None
        """
        
        if not os.path.isfile(filename):
            raise IOError("File '" + filename + "' does not exist.")
        
        data = json.load(open(filename))
        
        # check validation
        if "dvar-bounds" not in data:
            raise KeyError("Error in JSON format: " \
                           "Design variable bounds are not present.")
        
        if "constraints" not in data:
            raise KeyError("Error in JSON format: " \
                           "Constraints are not present.")
            

        population = data["population"]
        first_indv_key = list(population.keys())[0]
        for idx, name in enumerate(data["population"][first_indv_key].keys()):
            name = name.replace(" ", "")
            #self.__nameToColumnMap[name] = idx
            if name == 'dvar':
                for jdx, dvars in enumerate(sorted(data["population"][first_indv_key][name].keys())):
                    self.__dvarNameToColumnMap[dvars] = jdx
            elif name == 'obj':
                for jdx, objs in enumerate(sorted(data["population"][first_indv_key][name].keys())):
                    self.__objNameToColumnMap[objs] = jdx
            else:
                raise KeyError("Error in JSON format: " \
                           "Unexpected keys in population.")

        self.__nDvars       = len(self.__dvarNameToColumnMap)
        self.__nObjs        = len(self.__objNameToColumnMap)
        self.__nColumns     = self.__nDvars + self.__nObjs + 1 # + ID

    ##
    def __readJSONData(self, filename):
        """ Read in data

        Parameters
        ----------
        filename    : a generation file
    
        Returns
        -------
        None
    
        Notes
        -----
        Storage of columns: dvars, objs, ID
    
        Examples
        --------
        None
        """
        
        data      = json.load(open(filename))
        
        self.__dvarBounds = data["dvar-bounds"]
        self.__constraints = data["constraints"]
        population = data["population"]
        self.__nIndividuals = len(data["population"])
        
        table     = np.zeros((self.__nIndividuals, self.__nColumns))

        for i, pop in enumerate(population):
            for j, key in enumerate(population[str(pop)]):

                if key == 'dvar':
                    k = 0
                    for dvar, value in sorted(population[str(pop)][key].items()):
                        table[i, k] = float(value)
                        k += 1

                elif key == 'obj':
                    k = self.__nDvars
                    for obj, value in sorted(population[str(pop)][key].items()):
                        #print(obj,value)
                        table[i, k] = float(value)
                        k += 1
                else:
                    pass

            k = self.__nDvars + self.__nObjs
            table[i, k] = int(pop)

        return table
