##
# Usage of OptPilotJsonReader
#
# 1. Find all .json files of a directory, e.g. "./"
#   
#   optjson = OptPilotJsonReader("./")
#
# 2. Read in a generation file, e.g. 450
#   
#   optjson.readGeneration(450)
#
# 3. Obtain an individual
#
#   print ( optjson.getVariableNames() )
#   var = optjson.getVariableNames()[0]
#   print ( optjson.getIndividual(1, var) )
#

import json
import os
import numpy as np

class OptPilotJsonReader:
    """ Parsing of JSON files generated by Opt-Pilot

    Parameters
    ----------
    OptPilotJsonReader  : Check a directory for .json files and read in their format
    readGeneration      : Read a specific generation file
    getIndividual       : Obtain an individual [design variables, objectives, ID]
    getIndividualWithID : Obtain an individual with a specific ID [design variables, objectives, ID]
    getDesignVariables  : Returns all design variable names
    getObjectives       : Returns all objective names

    Returns
    -------
    None

    Notes
    -----
    None

    Examples
    --------
    Assume following JSON file:
    
    =====================================================
    {
        "name": "opt-pilot",
        "solutions": [
        {
                "ID": 0,
                "obj":
                {
                        "dpeak1": 10.37,
                        "dpeak2": 5.43,
                        "dpeak3_5": 14.1095
                }
                ,
                "dvar":
                {
                        "benergy": 0.0718672,
                        "phiinit": 113.653,
                        "prinit": -0.0191565,
                        "rinit": 2018.26
                }
        }
        ,
        {
                "ID": 18,
                "obj":
                {
                        "dpeak1": 5.95,
                        "dpeak2": 4.75,
                        "dpeak3_5": 17.6668
                }
                ,
                "dvar":
                {
                        "benergy": 0.0715704,
                        "phiinit": 110.517,
                        "prinit": -0.0122177,
                        "rinit": 2035.32
                }
        }
        ,
        {
                "ID": 2,
                "obj":
                {
                        "dpeak1": 1.84,
                        "dpeak2": 6.04,
                        "dpeak3_5": 19.2461
                }
                ,
                "dvar":
                {
                        "benergy": 0.0711942,
                        "phiinit": 107.097,
                        "prinit": -0.0198867,
                        "rinit": 2034.75
                }
        }
        ]
    }
    =====================================================
    
    
    import OptPilotJsonReader as optreader
    import sys
    
    try:
        
        # 1. Find all .json files of a directory, e.g. "./"
        optjson = optreader.OptPilotJsonReader("./")
        
        # 2. Read in a generation file, e.g. 1  
        optjson.readGeneration(1)
        
        # 3. Get all design variables
        dvars = optjson.getDesignVariables()
        
        print ( "Design variables: ", dvars )
        
        # 4. Get all objectives
        objs = optjson.getObjectives()
        
        print ( "Objectives: ", objs )
        
        # 5. Get an individual
        print ( optjson.getIndividual(0) )
        
        # 6. Get an individual with specific ID
        print ( optjson.getIndividualWithID(18) )
        
        # raise error
        print ( optjson.getIndividualWithID(1) )
    
    except:
        print ( sys.exc_info()[1] )

    """
    
    
    ##
    # @param directory to json files
    def __init__(self, directory):
        """ Parse a generation file

        Parameters
        ----------
        directory     : where the .json files are
    
        Returns
        -------
        an OptPilotJsonReader object
    
        Notes
        -----
        Raises a runtime error if
            - there are several several different basenames
            - no json file is found
    
        Examples
        --------
        None
        """
        
        self.__nJsonFiles = 0;
        self.__directory = directory
        self.__basename = ""
        self.__table = []
        
        ## name of the columns in the solution data
        #self.__nameToColumnMap = {}
        self.__objNameToColumnMap = {}
        self.__dvarNameToColumnMap = {}
        
        self.__nDvars = 0
        self.__nObjs  = 0
        self.__nColumns = 0
        self.__nIndividuals = 0
        
        tbasename = ""
        testfile = ""
        for f in os.listdir(directory):
            if f.endswith(".json"):
                self.__nJsonFiles += 1
                
                if self.__nJsonFiles == 1:
                    testfile = f
                
                tbasename = os.path.basename(f)
                
                tbasename = "_" + str.split(f, "_", 1)[1]
                
                # check if only one type of simulation
                if self.__basename != "" and tbasename != self.__basename:
                    raise RuntimeError("Several simulations with different name!")
                
                self.__basename = tbasename
        
        if self.__nJsonFiles == 0:
            raise RuntimeError("No json file found in directory '" + directory + "'.")
        
        # get mapping from first file (all others are the same)
        self.__buildNameToColumnMap(self.__directory + testfile)
        
        print ( "Found " + str(self.__nJsonFiles) + " json files." )
    
    
    ##
    def readGeneration(self, gen):
        """ Parse a generation file

        Parameters
        ----------
        gen     : the generation number
    
        Returns
        -------
        None
    
        Notes
        -----
        Raises a runtime error if generation file doesn't exist
    
        Examples
        --------
        None
        """
        
        filename = self.__directory + str(gen) + self.__basename
        
        if not os.path.isfile(filename):
            raise RuntimeError("File '" + filename + "' does not exist.")
        
        self.__table = self.__readJSONData(filename)
    
    
    ##
    def getIndividual(self, ind):
        """ Get invdividual is a list of [dvars, objs, ID]

        Parameters
        ----------
        ind     : the individual number (not the ID)
    
        Returns
        -------
        a list containing [design variables, objectives, ID]
    
        Notes
        -----
        Raises an index error if individual number is out of bounds
    
        Examples
        --------
        None
        """
        
        if ind > self.__nIndividuals - 1 or ind < 0:
            raise IndexError("Individual number is out of bounds.")
        
        return self.__table[ind, :]
    
    
    ##
    def getIndividualWithID(self, ID):
        """ Get invdividual with ID

        Parameters
        ----------
        ID     :    for which we want the data
    
        Returns
        -------
        a list containing [design variables, objectives, ID]
    
        Notes
        -----
        Raises a runtime error if there's no individual with given ID
    
        Examples
        --------
        None
        """
        
        idlist = self.__table[:, self.__nDvars + self.__nObjs].tolist()
        
        if ID not in idlist:
            raise RuntimeError("An individual with ID " + str(ID) + " is not present.")
        
        idx = idlist.index(ID)
        return self.__table[idx, :]
    
    
    ##
    def getDesignVariables(self):
        """ Obtain names of all design variables

        Parameters
        ----------
        None
    
        Returns
        -------
        a list containing all design variable names
    
        Notes
        -----
        None
    
        Examples
        --------
        None
        """
        return self.__dvarNameToColumnMap.keys()
    
    
    ##
    def getObjectives(self):
        """ Obtain names of all objectives

        Parameters
        ----------
        None
    
        Returns
        -------
        a list containing all design variable names
    
        Notes
        -----
        None
    
        Examples
        --------
        None
        """
        return self.__objNameToColumnMap.keys()
    
    
    ##
    def __buildNameToColumnMap(self, filename):
        """ Build data structures

        Parameters
        ----------
        filename    : a generation file
    
        Returns
        -------
        None
    
        Notes
        -----
        Assumes the ordering: [u'dvar', u'obj', u'ID']
    
        Examples
        --------
        None
        """
        
        if not os.path.isfile(filename):
            raise RuntimeError("File '" + filename + "' does not exist.")
        
        data = json.load(open(filename))
    
        for idx, name in enumerate(data["solutions"][0].keys()):
            name = name.replace(" ", "")
            #self.__nameToColumnMap[name] = idx
            if name == 'dvar':
                for jdx, dvars in enumerate(data["solutions"][0][name].keys()):
                    self.__dvarNameToColumnMap[dvars] = jdx
            elif name == 'obj':
                for jdx, objs in enumerate(data["solutions"][0][name].keys()):
                    self.__objNameToColumnMap[objs] = jdx
            elif name == 'ID':
                pass
            else:
                raise RuntimeError("Not expected json format.")
        
        self.__nDvars       = len(self.__dvarNameToColumnMap)
        self.__nObjs        = len(self.__objNameToColumnMap)
        self.__nColumns     = self.__nDvars + self.__nObjs + 1 # + ID
        self.__nIndividuals = len(data["solutions"])
        
        
    ##
    def __readJSONData(self, filename):
        """ Read in data

        Parameters
        ----------
        filename    : a generation file
    
        Returns
        -------
        None
    
        Notes
        -----
        Storage of columns: dvars, objs, ID
    
        Examples
        --------
        None
        """
        
        data      = json.load(open(filename))
        solutions = data["solutions"]
        
        table     = np.zeros((self.__nIndividuals, self.__nColumns))
        for i, solution in enumerate(solutions):
            for j, key in enumerate(solution):
                if key == 'dvar':
                    k = 0
                    for dvar, value in solution[key].iteritems():
                        table[i, k] = float(value)
                        k += 1
                elif key == 'obj':
                    k = self.__nDvars
                    for obj, value in solution[key].iteritems():
                        table[i, k] = float(value)
                        k += 1
                elif key == 'ID':
                    k = self.__nDvars + self.__nObjs
                    table[i, k] = int(solution[key])
        
        return table
